language: node_js

node_js:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SCOPE: lint
    - TEST_SCOPE: desktop_unit
    - TEST_SCOPE: mobile_unit

install:
  - yarn install

script:
  - if [ "${TEST_SCOPE}" == "lint" ]; then yarn lint; fi
  - if [ "${TEST_SCOPE}" == "desktop_unit" ]; then yarn test; fi
  - if [ "${TEST_SCOPE}" == "mobile_unit" ]; then MOBILE=1 yarn test; fi
